# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.8", "3.9", "3.10" ]

    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t preprocessing-ng .

    - name: Lint with flake8
      run: |
        docker run -it --rm -v "$(pwd)":/app preprocessing-ng /bin/bash -c "pip install flake8; flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics; flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics"

    - name: Test with pytest
      run: |
        docker run -it --rm -v "$(pwd)":/app preprocessing-ng /bin/bash -c "pip install pytest; pytest"
